version: '3.8'

services:
  db-mysql:
    image: mysql:8
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fileupload
      MYSQL_USER: springuser
      MYSQL_PASSWORD: 123456
    mem_limit: 1024m
    ports:
      - 3306:3306

  app-springboot:
    depends_on:
      - db-mysql
    build:
      context: .
      dockerfile: build.Dockerfile
      target: app
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/fileupload?serverTimezone=GMT%2B8&rewriteBatchedStatements=true
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: 123456
      SWAGGER_SERVICE: "true"
    mem_limit: 2048m
    ports:
      - 8080:8080
    links:
      - db-mysql
